stats_prefix.c: Check for NDEBUG before using total_written variable
When using NDEBUG assert macro is ineffective which is caught by latest
clang and reports that total_written is set but unused. Therefore check
for NDEBUG to make sure assert is used only when its effective

Fixes
error: variable 'total_written' set but not used [-Werror,-Wunused-but-set-variable]
    size_t size = 0, written = 0, total_written = 0;
                                  ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>